# Generated by Django 3.1.1 on 2020-11-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='error',
            field=models.CharField(max_length=100),
        ),
    ]
